name: Deploy with Tags1

on:
  workflow_dispatch:

jobs:
  get_tags:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.get_tags.outputs.tags }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get the 5 most recent tags
        id: get_tags
        run: |
          TAGS=$(git tag --sort=-creatordate | head -n 5)
          echo "tags=$TAGS" >> $GITHUB_ENV
          echo "::set-output name=tags::$TAGS"

  deploy:
    needs: get_tags
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy code for the selected tag
        run: |
          echo "Available tags: ${{ needs.get_tags.outputs.tags }}"
          echo "Deploying tag: ${{ github.event.inputs.tag }}"
          git checkout ${{ github.event.inputs.tag }}
          # 这里执行具体的部署命令
