name: Deploy logic on Master

on:
  workflow_dispatch:  # 允许手动触发工作流
    inputs:
      environment:  # 针对 master 分支定义输入参数选择部署环境
        description: 'Select the deployment environment'
        required: true
        default: 'UAT'
        type: choice
        options:
          - UAT
          - PROD
  workflow_run:
      workflow: ["Release (tag)"]
      types:
        - completed
jobs:
  deploy-uat:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy UAT
        run: |
          echo "Here is deploying UAT!"

  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Prod
        run: |
          echo "Here is deploying PROD!"
  
