name: Deploy Workflow

on:
  push:
    branches:
      - develop  # 监听 develop 分支的 push 事件
      - master   # 监听 master 分支的 push 事件
  workflow_dispatch:  # 允许手动触发工作流
    inputs:
      environment:  # 针对 master 分支定义输入参数选择部署环境
        description: 'Select the deployment environment'
        required: true
        default: 'UAT'
        type: choice
        options:
          - UAT
          - PROD

jobs:
  deploy_DEV:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/develop' }}  # 只在 develop 分支上执行
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to DEV environment
        run: echo "Deploying to DEV environment..."

  deploy_master:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}  # 只在 master 分支上执行
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine environment
        run: |
          echo "Selected environment: ${{ github.event.inputs.environment }}"

      - name: Deploy to UAT
        if: ${{ github.event.inputs.environment == 'UAT' }}  # 如果选择了 UAT 环境
        run: echo "Deploying to UAT environment..."

      - name: Deploy to PROD
        if: ${{ github.event.inputs.environment == 'PROD' }}  # 如果选择了 PROD 环境
        run: echo "Deploying to PROD environment..."
