name: Deploy logic on Master

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
      
  workflow_dispatch:  # 允许手动触发工作流
    inputs:
      environment:  # 针对 master 分支定义输入参数选择部署环境
        description: 'Select the deployment environment'
        required: true
        default: 'UAT'
        type: choice
        options:
          - UAT
          - PROD
jobs:
  deploy-uat:
    if: |
      github.ref == 'refs/heads/master' ||
      startsWith(github.ref, 'refs/tags/v')
      
    runs-on: ubuntu-latest

    steps:
      - name: Deploy UAT
        run: |
          echo "Here is deploying UAT!"

  
