#name: Deploy logic on develop
#
#on:
#  push:
#    branches:
#      - develop
#
#jobs:
#  deploy-uat:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Deploy DEV
#        run: |
#          echo "Here is deploying DEV!"
#
#  deploy-prod:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Deploy QA
#        run: |
#          echo "Here is deploying QA!"
#

name: Display env variables

on:
  push

jobs:
  display:
    runs-on: ubuntu-latest
    env:
      TEST_ENV: MY_MAC_AIRs
    steps:
      - name: display_customized_env
        id: display_customized_env
        run: |
          echo '${{ env.TEST_ENV }}'
          echo "again, show: $TEST_ENV"
          echo "test=hello" >> "$GITHUB_OUTPUT"
      - name: display_github_env
        id: display_github_env
        run: |
          echo '${{ toJSON(github)}}'
      - name: display_github_output
        id: display_github_output
        run: |
          echo '${{ steps.display_customized_env.outputs.test }}'

      - name: display_github_DEF_ENV_VARIABLES
        run: |
          echo "$GITHUB_WORKFLOW"