name: Monitor Master and Tags

on:
  push:
    branches:
      - master  # Trigger on pushes to the master branch
    tags:
      - 'v*'    # Trigger on tags that start with "v"
  workflow_run:
    workflows: [ "Release (tag)" ]
    types:
      - completed

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display Event Info
        run: |
          if [[ "${GITHUB_REF}" == refs/heads/master ]]; then
            echo "Push detected on master branch."
          elif [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            echo "Tag with 'v' prefix detected: ${GITHUB_REF}"
          fi
