name: Java Maven Workflow

on:
  # 手动触发 workflow，允许选择环境
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to deploy'  # 部署时选择环境
        required: true
        default: 'UAT'
        type: choice
        options:
          - UAT
          - PROD

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up deployment environment
        run: |
          if [ "${{ github.event.inputs.environment }}" == "UAT" ]; then
            echo "Deploying to UAT environment"
            # 在这里添加 UAT 环境的部署逻辑
          elif [ "${{ github.event.inputs.environment }}" == "PROD" ]; then
            echo "Deploying to PROD environment"
            # 在这里添加 PROD 环境的部署逻辑
          fi
