name: Java Maven Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # 可以选择其他发行版，例如 'zulu'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install

      - name: Package the application
        run: mvn package

      - name: Create Git tag
        id: tag_step
        run: |
          # 获取当前的提交哈希
          COMMIT_HASH=$(git rev-parse --short HEAD)
          # 定义标签的名称，可以自定义
          TAG_NAME="v1.0.${COMMIT_HASH}"
          # 创建标签
          git tag $TAG_NAME
          # 推送标签到远程仓库
          git push origin $TAG_NAME

      - name: Output tag
        run: echo "Tag ${{ steps.tag_step.outputs.tag_name }} created and pushed."