name: Terraform Prod Deployment

on:
  push:
    paths:
      - 'terraform/prod/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      # Step 3: Configure AWS credentials from Secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      # Step 4: Terraform Init for Prod
      - name: Terraform Init
        run: terraform init
        working-directory: terraform/prod

      # Step 5: Terraform Plan for Prod
      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform/prod

      # Step 6: Terraform Apply for Prod
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform/prod
